### ISSUE TITLE
Maintainer needed?

### ISSUE THREAD

**Issue by mifi** [kwhitley/treeize#48]
First of all thanks for creating this! I'm an avid user of treeize and knex. I can see that this repo has not been updated in 5 years and although it works nicely, has some minor issues. If you need help maintaining I can volunteer.

**Comment by vrepsys** [comment]
@mifi since there hasn't been a reply for over a year, you should consider forking Treeize.

**Comment by kwhitley** [comment]
Dang, this was just the kick in the inbox that I needed - thanks @vrepsys!

@mifi - Happy to add you as a collab!  Mind hopping over to https://discord.gg/3hNdaqhe8M to discuss?

**Comment by mifi** [comment]
I migrated my codebases to Objection and am not using Treeize any more, so I don’t think i’d be a good fit as a maintainer anymore unfortunately. Closing this
